### ISSUE TITLE
会有 AutoProxy 规则版本吗？

### ISSUE THREAD

**Issue by oscargong** [ky0ncheng/gfvvlist#2]

**Comment by 1a57danc3** [comment]
主流系統都系統級支持pac規則 autoproxy我認爲沒必要了

如果你是chrome用戶 我推薦SwitchyOmega這個擴展控制代理

**Comment by oscargong** [comment]
是 Chrome 用户，且已经在使用 SwitchyOmega 。
之所以需要 AutoProxy ，是希望使用「自动切换模式」，以和其余规则结合（像视频广告屏蔽插件ADfree）使用。

## ![qq20150906-1 2x](https://cloud.githubusercontent.com/assets/7035787/9702399/8c69085c-548d-11e5-9cdd-c07aba9d380c.jpg)

![qq20150906-2 2x](https://cloud.githubusercontent.com/assets/7035787/9702423/a28c11aa-548e-11e5-8615-3af751a4f679.jpg)

**Comment by 1a57danc3** [comment]
如果使用 shadowsocks，可以使用 gui 的客户端  支持全局代理并使用 pac 规则自定义， 把我这份白名单粘贴进去  修改下端口就可以了

因为我这个是白名单  如果有国内网站也使用了 shadowsocks 代理  可以用 Omega 进行自定义规则

**Comment by 1a57danc3** [comment]
http://hi.akarin.xyz/t/10

適用於扩展程序Proxy SwitchyOmega的白名單規則

**Comment by oscargong** [comment]
It Works! THANK YOU!

**Comment by oscargong** [comment]
我的 ME294 (i7-4850HQ) 在 SwitchyOmega 里编辑一下这个列表，每次操作都会有 2s 以上的卡顿……😂

**Comment by 1a57danc3** [comment]
這很正常
