### ISSUE TITLE
新手关于gfvvlist黑白规则的使用

### ISSUE THREAD

**Issue by ghost** [ky0ncheng/gfvvlist#4]
很抱歉打扰到您,但作为一个新手用户来说,我实在不懂怎么操作.
请问,是否是需要安装Python才能够使用呢?
因为并没发现var ip_address或者var proxy_type

**Comment by 1a57danc3** [comment]
成品 https://github.com/akar1nchan/gfvvlist/tree/master/src

可以直接使用

因爲二進製化了 代碼並不具備可讀性 請使用python命令(不帶-m參數)生成可讀性的pac文件

**Comment by ghost** [comment]
@akar1nchan 在线恢复BlackListsOmegaOptions.bak，AUTO情景会出现“此情景模式使用存储空间过多，因此无法进行同步。”

**Comment by 1a57danc3** [comment]
同步條目過多無法同步 請關閉同步
